### ISSUE TITLE
Social Media Image

### ISSUE THREAD

**Issue by xavier506** [lacchain/eosio.lacchain.net#53]
Social preview Image is not the right size
Upload an image to customize your repository’s social media preview.

Images should be at least 640×320px (1280×640px for best display).
Download template

**Comment by xavier506** [comment]
[](url)![repository-open-graph-template (3)](https://user-images.githubusercontent.com/5632966/122093909-c78d1f80-cdc8-11eb-88b8-a21c94a90ee5.png)

**Comment by Johannayee** [comment]
Hola! por acá les dejo las distintas opciones 
![Preview-LACCHAIN-1](https://user-images.githubusercontent.com/85965202/122305592-65194980-cec4-11eb-8630-d0095182a436.png)
![Preview-LACCHAIN-2](https://user-images.githubusercontent.com/85965202/122305594-664a7680-cec4-11eb-8f46-d6bc7b197f7c.png)
![Preview-LACCHAIN-3](https://user-images.githubusercontent.com/85965202/122305596-664a7680-cec4-11eb-809e-2f3fb08320ce.png)
![Preview-LACCHAIN-4](https://user-images.githubusercontent.com/85965202/122305597-66e30d00-cec4-11eb-8b54-9c121e555dab.png)
![Preview-LACCHAIN-5](https://user-images.githubusercontent.com/85965202/122305600-677ba380-cec4-11eb-92da-cc307d55b7ca.png)

**Comment by Johannayee** [comment]
Cualquier cosa pueden revisarlas y si necesitan un ajuste yo con gusto les ayudo

**Comment by xavier506** [comment]
![image](https://user-images.githubusercontent.com/5632966/122324766-999dfd00-cee6-11eb-8206-2469520ce579.png)
me gusta esta

**Comment by xavier506** [comment]
![image](https://user-images.githubusercontent.com/5632966/122325111-33fe4080-cee7-11eb-888d-c820fdf51017.png)

a mi me gustan estas dos

**Comment by ldrojas** [comment]
Tambien la segunda que compartió Xavier @Johannayee
