### ISSUE TITLE
Agregar iconos a navbar versión movil

### ISSUE THREAD

**Issue by ldrojas** [lacchain/eosio.lacchain.net#63]
- [x] Buscar iconos @Johannayee https://icons8.com/
- [x] Agregar iconos @AngeloCG97 
![image](https://user-images.githubusercontent.com/51149817/122262290-7f3a3400-ce92-11eb-9617-65a6ae47d314.png)

**Comment by Johannayee** [comment]
Hola! por acá les dejo el link del drive donde podrán ver los íconos
https://drive.google.com/drive/u/2/folders/1RPpnmOCJhSiX85ogEWLSM91aOaUcdEzU
